import re
from rapidfuzz import process, fuzz

_category_cache: list = []

def _get_categories() -> list:
    global _category_cache
    if _category_cache:
        return _category_cache
    try:
        from database.sql_retriever import get_all_categories
        _category_cache = get_all_categories()
    except Exception:
        _category_cache = ["electronics", "fashion", "beauty", "gaming", "groceries"]
    return _category_cache


def resolve_references(user_message: str, context: dict) -> str:
    """
    Replaces conversational pronouns and ordinals with explicit active entities from persistent memory.
    Example: "What is the price of the first one?" -> "What is the price of ASUS ROG?"
    """
    text = user_message
    lower_text = text.lower()
    
    ordinals = {"first": 0, "1st": 0, "second": 1, "2nd": 1, "third": 2, "3rd": 2, "last": -1}
    
    # Resolve ordinals targeting lists generated by recommendation/inventory queries
    for word, idx in ordinals.items():
        if re.search(fr'\b{word}\s+(one|item|product)\b', lower_text):
            if context.get("last_shown_items") and len(context["last_shown_items"]) > (idx if idx >= 0 else 0):
                item = context["last_shown_items"][idx]
                text = re.sub(fr'\b{word}\s+(one|item|product)\b', item, text, flags=re.IGNORECASE)
                lower_text = text.lower()
                
    # Resolve implicit pronouns targeting singular active entities
    pronoun_pattern = r'\b(it|that|this|those|same one)\b'
    if re.search(pronoun_pattern, lower_text):
        if context.get("active_product"):
            text = re.sub(pronoun_pattern, context["active_product"], text, flags=re.IGNORECASE)
        elif context.get("active_category"):
            text = re.sub(pronoun_pattern, context["active_category"], text, flags=re.IGNORECASE)
        elif context.get("active_order_id"):
            text = re.sub(pronoun_pattern, context["active_order_id"], text, flags=re.IGNORECASE)
            
    return text

def fuzzy_match_category(text: str):
    """
    Fuzzy matching against live DB categories with typo tolerance.
    """
    categories = _get_categories()
    text_lower = text.lower().strip()
    text_words = set(text_lower.split())

    # Pass 1: exact full-name match inside user text (e.g. "i want mens bags" → "Mens Bags")
    for cat in categories:
        if cat.lower() in text_lower:
            return cat

    # Pass 2: all user words are present in the category name (word-level, avoids "mens" ⊂ "womens")
    for cat in categories:
        cat_words = set(cat.lower().split())
        if text_words and text_words.issubset(cat_words):
            return cat

    # Pass 3: fuzzy token-set match for typos / pluralization
    lower_cats = [c.lower() for c in categories]
    match = process.extractOne(text_lower, lower_cats, scorer=fuzz.token_set_ratio)
    if match and match[1] >= 65:
        return categories[lower_cats.index(match[0])]

    return None

def detect_continuation(user_message: str):
    """
    Detects if the user is just uttering a continuation phrase to inherit the previous active intent.
    """
    continuation_phrases = ["yes", "okay", "show more", "tell me", "what else", "continue", "more", "sure", "yep", "yeah"]
    if user_message.lower().strip() in continuation_phrases:
        return True
    return False
